//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project123.Components.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentPriorityHistory
    {
        public int ChangeID { get; set; }
        public int AgentID { get; set; }
        public int OldPriorityLevel { get; set; }
        public int NewPriorityLevel { get; set; }
        public System.DateTime ChangeDate { get; set; }
    
        public virtual Agents Agents { get; set; }
    }
}
