//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project123.Components.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentRequests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgentRequests()
        {
            this.RequestDetails = new HashSet<RequestDetails>();
        }
    
        public int RequestID { get; set; }
        public int AgentID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int Status_Id { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual Agents Agents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestDetails> RequestDetails { get; set; }
        public virtual AgentRequestStatus AgentRequestStatus { get; set; }
    }
}
