//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project123.Components.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMovement
    {
        public int id { get; set; }
        public int idCard { get; set; }
        public System.DateTime MovementTime { get; set; }
        public string Location { get; set; }
    
        public virtual EmployeeCard EmployeeCard { get; set; }
    }
}
