//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project123.Components.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.MaterialStockHistory = new HashSet<MaterialStockHistory>();
            this.ProductionMaterial = new HashSet<ProductionMaterial>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public int idMaterialType { get; set; }
        public Nullable<int> idSupplier { get; set; }
        public decimal QuantityPerPackage { get; set; }
        public int Unit { get; set; }
        public decimal StockQuantity { get; set; }
        public Nullable<decimal> MinStockLevel { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public decimal Cost { get; set; }
    
        public virtual MaterialType MaterialType { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Unit Unit1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialStockHistory> MaterialStockHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionMaterial> ProductionMaterial { get; set; }
    }
}
