//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project123.Components.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.MaterialStockHistory = new HashSet<MaterialStockHistory>();
            this.ProductionMaterials = new HashSet<ProductionMaterials>();
        }
    
        public int MaterialID { get; set; }
        public string Name { get; set; }
        public int MaterialType_id { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public decimal QuantityPerPackage { get; set; }
        public int Unit { get; set; }
        public decimal StockQuantity { get; set; }
        public Nullable<decimal> MinStockLevel { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public decimal Cost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialStockHistory> MaterialStockHistory { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionMaterials> ProductionMaterials { get; set; }
        public virtual MaterialType MaterialType { get; set; }
        public virtual Unit Unit1 { get; set; }
    }
}
