//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project123.Components.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductManagementEntities : DbContext
    {
        public ProductManagementEntities()
            : base("name=ProductManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgentPriorityHistory> AgentPriorityHistory { get; set; }
        public virtual DbSet<AgentRequests> AgentRequests { get; set; }
        public virtual DbSet<AgentRequestStatus> AgentRequestStatus { get; set; }
        public virtual DbSet<AgentType> AgentType { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<MaterialStockHistory> MaterialStockHistory { get; set; }
        public virtual DbSet<MaterialType> MaterialType { get; set; }
        public virtual DbSet<ProductionMaterials> ProductionMaterials { get; set; }
        public virtual DbSet<ProductPriceHistory> ProductPriceHistory { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductType> ProductType { get; set; }
        public virtual DbSet<RequestDetails> RequestDetails { get; set; }
        public virtual DbSet<SalesPoints> SalesPoints { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<Workshop> Workshop { get; set; }
        public virtual DbSet<Agents> Agents { get; set; }
        public virtual DbSet<AgentSalesHistory> AgentSalesHistory { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
