//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project123.Components.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriorityHistory
    {
        public int id { get; set; }
        public Nullable<int> idAgent { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> idPriority { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Priority Priority { get; set; }
    }
}
