//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project123.Components.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Production = new HashSet<Production>();
            this.ProductList = new HashSet<ProductList>();
            this.ProductPriceHistory = new HashSet<ProductPriceHistory>();
        }
    
        public int id { get; set; }
        public string Article { get; set; }
        public string Name { get; set; }
        public Nullable<int> idProductType { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> WeightWithPackage { get; set; }
        public string WeightWithoutPackage { get; set; }
        public byte[] QualityCertificate { get; set; }
        public string Standart { get; set; }
        public string Size { get; set; }
        public Nullable<decimal> MinAgentPrice { get; set; }
    
        public virtual ProductType ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Production> Production { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductList> ProductList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPriceHistory> ProductPriceHistory { get; set; }
    }
}
