//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project123.Components.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPriceHistory
    {
        public int id { get; set; }
        public Nullable<int> idProduct { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> NewPrice { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
