//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project123.Components.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Production()
        {
            this.ProductionMaterial = new HashSet<ProductionMaterial>();
        }
    
        public int id { get; set; }
        public Nullable<int> idProduct { get; set; }
        public Nullable<decimal> Time { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<int> idWorkshop { get; set; }
        public Nullable<int> RequiredEmployees { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Workshop Workshop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionMaterial> ProductionMaterial { get; set; }
    }
}
